circuit_breaker.circuit_breaker_config.*:
  type: config_entity
  label: 'Circuit breaker configuration'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    threshold:
      type: integer
      label: 'Failure threshold'
    test_retry_min_interval:
      type: integer
      label: 'Minimum interval for randomised retry'
    test_retry_max_interval:
      type: integer
      label: 'Maximum interval for randomised retry'
