<?php

/**
 * @file
 * Circuit breaker test module.
 */

/**
 * Implements hook_cron().
 */
function circuit_breaker_test_cron() {
  $cb = Drupal::service('circuit_breaker.factory')->load('test');
  $cb->setRetryAllowed(TRUE);
  try {
    $cb->execute(function () {
      Drupal::logger('cbtest')->info('cron executed ok');
      return 'ok';
    });
  }
  catch (Throwable $exception) {
    Drupal::logger('cbtest')->error('exception thrown: ' . $exception->getMessage());
  }
}
